// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChapterService is an autogenerated mock type for the ChapterService type
type ChapterService struct {
	mock.Mock
}

type mockConstructorTestingTNewChapterService interface {
	mock.TestingT
	Cleanup(func())
}

// NewChapterService creates a new instance of ChapterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChapterService(t mockConstructorTestingTNewChapterService) *ChapterService {
	mock := &ChapterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
